# Generated by Django 5.0.2 on 2024-02-14 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agegender',
            name='camera',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='agegender', to='dashboard.camera'),
            preserve_default=False,
        ),
    ]
